### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by joy88** [xtuhcy/socks5-netty#1]
I got Exception:
It's strange that:
I visited url https://www.baidu.com, it works well, 
but when I visited https://www.google.com,
it throws an exception:
Exception in thread "main" java.net.ProtocolException: unexpected end of stream
	at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:398)
	at okio.RealBufferedSource.read(RealBufferedSource.java:46)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:56)
	at okio.InflaterSource.refill(InflaterSource.java:101)
	at okio.InflaterSource.read(InflaterSource.java:62)
	at okio.GzipSource.read(GzipSource.java:80)
	at okio.Buffer.writeAll(Buffer.java:1005)
	at okio.RealBufferedSource.readString(RealBufferedSource.java:190)
	at okhttp3.ResponseBody.string(ResponseBody.java:175)
	at com.geccocrawler.socks5.test.HttpProxyClient.main(HttpProxyClient.java:42)

Here was my code:
user, password, host, port, I'm sure it's correct:
public static void main(String[] args) throws Exception {
		final String user = "x";
		final String password = "y";
		
		Proxy proxyTest = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("115.137.1.15", 6080));
		
		java.net.Authenticator.setDefault(new java.net.Authenticator()
		{
			private PasswordAuthentication authentication = new PasswordAuthentication(user, password.toCharArray());

			@Override
			protected PasswordAuthentication getPasswordAuthentication()
			{
				return authentication;
			}
		});

		OkHttpClient client = new OkHttpClient.Builder().proxy(proxyTest).build();
		Request request = new Request.Builder().url("https://www.google.com").build();
		Response response = client.newCall(request).execute();
		System.out.println(response.code());
		System.out.println(response.body().string());
		
		client.dispatcher().executorService().shutdown();
		client.connectionPool().evictAll();
	}

**Comment by joy88** [comment]
I got the answer:
https://github.com/square/okhttp/issues/1490
add the header "Accept-Encoding: identity" on the client side.
